### ISSUE TITLE
Make JS process modules use CommonJS exports

### ISSUE THREAD

**Issue by dflemstr** [dflemstr/rq#104]
Currently, process modules such as `prelude.js` insert their processes in the global scope. It might be more sane to have them export processes selectively via `exports.id = ...` for example. `rq` should then load files like these as modules.

**Comment by dflemstr** [comment]
There's also the possibility to switch to ES6 modules now.

**Comment by XVilka** [comment]
Irrelevant now, I guess?

**Comment by dflemstr** [comment]
Yes, JS support was removed!
