### ISSUE TITLE
Automatically load JS functions from file

### ISSUE THREAD

**Issue by sveinnfannar** [dflemstr/rq#105]
It would be nice if I could have my own JavaScript functions acting as jq processes when transforming data.
`rq` could search for `.rq.js` in the same directory (and possibly `~/.rq.js` too).

**Comment by dflemstr** [comment]
`rq` currently looks for files according to the XDG directory spec, so for example proto files are found in `~/.local/share/rq/proto`, `/usr/share/rq/proto` and `/usr/local/share/rq/proto`.

Maybe for consistency we could also add a `rq js add <file>` command.

**Comment by Stebalien** [comment]
>  search for `.rq.js` in the same directory

 :-1: :heavy_multiplication_x: :100:

From a security perspective, that would not be a good idea.

**Comment by sveinnfannar** [comment]
Very good point

**Comment by fentas** [comment]
it's kind of an old issue but is it possible to add js functions in general without recompiling `rq`?

**Comment by XVilka** [comment]
Irrelevant now, I guess?

**Comment by dflemstr** [comment]
Yes, JS support was removed!
