### ISSUE TITLE
Switch serde_json and v8 dependencies to Crate version

### ISSUE THREAD

**Issue by aristidb** [dflemstr/rq#144]
I'm trying to add a package for rq to my favorite Linux distribution, which has semi-automatic support for Crates.io packages.

rq currently has two dependencies which are not in the registry, which makes the process quite a bit harder.

- serde_json
- v8

**Comment by dflemstr** [comment]
I can't use the crate version of `serde_json` because I'm using some not yet released features. I'll switch to the crate version of `v8` once the `serde_json` version is released.

**Comment by aristidb** [comment]
Sounds good.

(I ended up giving up on packaging the package for now because my distro's latest version of v8 is 5.4.232, and I think the minimum version required by v8 is 5.4.SOMETHINGHIGHER. It seems that Maybe<>::To was only added later in the 5.4.x release series. And I'm not brave enough to update v8.)

**Comment by dtolnay** [comment]
The not-yet-released features were released in serde_json 0.9.0.
