### ISSUE TITLE
Unable to parse protos defined within a package

### ISSUE THREAD

**Issue by apoorv-gupta** [dflemstr/rq#153]
I couldn't get rq to work with some proto files on my local machine. PTAL.

https://gist.github.com/apoorv-gupta/d1440525e7d3ec0b5032c51981ccb0de

**Comment by dflemstr** [comment]
Hey @apoorv-gupta! Do you have `protoc` installed and is it on your path?

I was thinking about linking `libprotoc` in `rq` and shipping it as part of the binary but I haven't done that yet, so you need `protoc` on your path for now.

Also, `rq` interprets the binary protobuf format, not the text format right now.

**Comment by apoorv-gupta** [comment]
That must be why. I don't have protoc in my PATH.
I wanted to use rq to run some validations on a collection of Protos and transform into a collection of another Protos. I am looking for a rule-based approach that depends on the value of fields. As you can tell, it is a semi automated process, with some input from a domain expert.

⁣Sent from TypeApp ​
