### ISSUE TITLE
Generic install failed: server SSL-certification issue

### ISSUE THREAD

**Issue by nirfse** [dflemstr/rq#154]
Hello, general installation method isn't currently available since host https://sh.dflemstr.name has SSL-cerification issue.

`$ curl -sSLf https://sh.dflemstr.name/rq | bash`
`curl: (60) server certificate verification failed [...]`

**Comment by dflemstr** [comment]
@nirfse thanks for the heads up, the certificate had been renewed but nginx hadn't been restarted with the new certificate. I'll make sure it doesn't happen again
