### ISSUE TITLE
Docs 404

### ISSUE THREAD

**Issue by sevagh** [dflemstr/rq#155]
Hello. I'm trying to use this library but all the doc links are 404ing:

e.g.:

* https://dflemstr.github.io/rq/serde-protobuf/
* https://dflemstr.github.io/rq/serde_protobuf/de/index.html

Have they moved?

I followed the link from crates.io: https://crates.io/crates/serde_protobuf

**edit**

Found this link that works: https://docs.rs/serde-protobuf/0.5.0/serde_protobuf/de/index.html

Maybe you could update that in crates.io?

**Comment by dflemstr** [comment]
@sevagh sorry totally missed this, will do!
