### ISSUE TITLE
Separate serde-protobuf and share maintenance load

### ISSUE THREAD

**Issue by sevagh** [dflemstr/rq#164]
Hello,

If you recall I submitted a patch for serde-protobuf to support serde 1.0+.

I use the serde-protobuf crate in an application and may use it more soon. Does it make sense to:

* Split the repo away from rq
* Share the maintenance load? I'm not experienced at maintaining open source projects but I have a vested interest in serde-protobuf and I think as protobuf becomes more important in the future more people will rely on this crate if it stays up to date regularly

**Comment by dflemstr** [comment]
Sounds reasonable to me. I can split it out right now!
