### ISSUE TITLE
Windows binary?

### ISSUE THREAD

**Issue by MatrixView** [dflemstr/rq#169]
I'd love to use RQ... but I'm running Windows.  I hope you'll make a release for it. Is it in your roadmap?
Thanx in advance!

**Comment by 20iahazban** [comment]
any update?

**Comment by Slach** [comment]
Install RUST
https://win.rustup.rs/

after that use
```
cargo install record-query
```

**Comment by dflemstr** [comment]
There is now an official Windows binary in the Releases of this repo!
