### ISSUE TITLE
When will there be crates.io and github release with raw (-r -R) input/output options?

### ISSUE THREAD

**Issue by vi** [dflemstr/rq#188]

**Comment by dflemstr** [comment]
It's quite tricky to release this crate in its current form due to the complicated V8 dependency.  For now, a master build of the program is available, let me know if there is a specific reason why you need a Github or crates.io release!

**Comment by vi** [comment]
What is a master build? Do you mean not a pre-built rq, but the source code from master? That stops "let's workaround missing/outdated v8 by just using static pre-built rq" scenario.

**Comment by vi** [comment]
Thanks for pointing out, I missed that table at README (or assumed it would point to Github Releases that I had already checked)

**Comment by zenlor** [comment]
sadly last binaries are not compiled with the raw flag:

```./rq -r
Unknown flag: '-r'

Usage:
  rq (--help|--version)
  rq [-j|-a|-c|-h|-m|-p <type>|-t|-y] [-J|-A <type>|-C|-H|-M|-P <type>|-T|-Y] [--format <format>] [-l <spec>|-q] [--trace] [--] [<query>]
  rq [-l <spec>|-q] [--trace] protobuf add <schema> [--base <path>]```

**Comment by dflemstr** [comment]
You might be using the musl build which according to the table in the README is still stuck on 0.9

I need to fix the build environment containers for musl builds, they are a bit broken right now.... That's why I haven't had time to fix it, because it's a deep rabbit hole involving cross-compiling libstdc++ to musl :)

**Comment by mikaelstaldal** [comment]
Now the Linux glibc build is also broken. Only the MacOS X build works at the moment.

**Comment by dflemstr** [comment]
This should now be fixed, and the latest version should be released
