### ISSUE TITLE
I was refused a connection!

### ISSUE THREAD

**Issue by JensRantil** [dflemstr/rq#190]
...sad story. Example:
```bash
$ curl -sSLf https://sh.dflemstr.io/rq
curl: (7) Failed to connect to sh.dflemstr.io port 443: Connection refused
```
Got the command from https://github.com/dflemstr/rq/blob/master/doc/installation.md#generic.

**Comment by dflemstr** [comment]
Should be fixed now!  An unattended upgrade of the server broke it :(
