### ISSUE TITLE
rq failed to parse valid toml

### ISSUE THREAD

**Issue by jsirex** [dflemstr/rq#201]
Probably, this is related to `toml-rs` library, not sure is it fixed already.

Dots in nested keys are valid toml, however:

```bash
rq --version && echo "foo.bar.baz = 125" | rq -t
```
Results to:
```
v0.10.4
[ERROR] [rq] Encountered: expected an equals, found a period at line 1
[ERROR] [rq] (Re-run with --trace or RUST_BACKTRACE=1 for a backtrace)
```

Relates to: https://github.com/habitat-sh/habitat/issues/6578

**Comment by dflemstr** [comment]
This should now be working since v1.0.0!
