### ISSUE TITLE
Is rq still a *query* tool?

### ISSUE THREAD

**Issue by Gerrit-K** [dflemstr/rq#207]
I've come across `rq` while looking for an alternative to [`jq`](https://stedolan.github.io/jq/) two days ago and I still didn't find any documentation on the query syntax. The "Tutorial" section just shows how to pretty-print JSON. It appears that there once were several other sections in the docs about the "query" aspect, but they [are gone since 1.0](https://github.com/dflemstr/rq/commit/72eeba9270ac3d21148805d316ebd3b065d71dbf#diff-e8760c4ca09afa252994b0d8d9c89827). Is it still possible to actually *query* any data read by `rq`?

PS: others seem to struggle with the current documentation as well, e.g. #200

**Comment by dflemstr** [comment]
I've been trying to ramp up rq development after a long break due to it being super difficult to maintain the Javascript-based query engine.  I have plans to re-add query functionality to the tool, but I'm not 100% sure of what that should look like.  Do you have any input?  Maybe we could create a discussion "issue" where we try to design the new query language.

**Comment by Gerrit-K** [comment]
Sorry for the delay. I can imagine that maintaining open source projects sometimes takes a lot of time and commitment. And that's a fair point. To me (regarding this issue) it would just suffice to add a noticeable disclaimer at the README so that every new visitor is aware of the current state (and maybe where to find old releases and their documentation).

Regarding the ramp-up: I really like the idea of a cross-format querying tool, but I can also imagine that it will be difficult to find a syntax that fits multiple formats while still being flexible and reasonably easy to use. If you want to go towards that direction, then yes, I think a separate (pinned) issue for discussion would be a good idea. If you want to focus on the transformation functionality instead, I would suggest to choose another name (or migrate the code to a fresh new repository) to avoid confusion.

**Comment by dflemstr** [comment]
Did as you suggested, I will close this issue and encourage others to follow up through #208 instead.

**Comment by pickfire** [comment]
rq seemed like a conversion tool after reading the docs, like what I did for https://github.com/pickfire/babelfish
